version: 2

sources:
  - name: clean
    schema: clean
    description: Projet dataset rclean
    tables:

      - name: IPS_colleges
        identifier: IPS_colleges
        description: Indice de positionnement social des collèges

      - name: IPS_ecoles
        identifier: IPS_ecoles
        description: Indice de positionnement social des écoles

      - name: IPS_lycees
        identifier: IPS_lycees
        description: Indice de positionnement social des lycées

      - name: annuaire2
        identifier: annuaire
        description: Annuaire des établissements

      - name: baccalaureat_par_academie
        identifier: baccalaureat_par_academie
        description: Données baccalauréat par académie


      - name: baccalaureat_par_departement
        identifier: baccalaureat_par_departement
        description: Données baccalaureat_par_departement


      - name: brevet_par_etablissement
        identifier: brevet_par_etablissement
        description: Données du brevet par établissement

      - name: effectif_colleges
        identifier: effectif_colleges
        description: Effectifs des collèges

      - name: effectif_lycee
        identifier: effectif_lycee
        description: Effectifs des lycées

      - name: etablissements_ecole_prioritaire
        identifier: prioritaires
        description: Établissements relevant de l’éducation prioritaire

      - name: iva_colleges
        identifier: IVA_colleges
        description: Indicateurs de valeur ajoutée des collèges

      - name: iva_lycees
        identifier: IVA_lycees
        description: Indicateurs de valeur ajoutée des lycées
